// Generated by 'unplugin-auto-import'
export {}
declare global {
  const batch: typeof import('@preact/signals')['batch']
  const computed: typeof import('@preact/signals')['computed']
  const effect: typeof import('@preact/signals')['effect']
  const signal: typeof import('@preact/signals')['signal']
  const useCallback: typeof import('preact/hooks')['useCallback']
  const useComputed: typeof import('@preact/signals')['useComputed']
  const useContext: typeof import('preact/hooks')['useContext']
  const useEffect: typeof import('preact/hooks')['useEffect']
  const useMemo: typeof import('preact/hooks')['useMemo']
  const useReducer: typeof import('preact/hooks')['useReducer']
  const useRef: typeof import('preact/hooks')['useRef']
  const useSignal: typeof import('@preact/signals')['useSignal']
  const useSignalEffect: typeof import('@preact/signals')['useSignalEffect']
  const useState: typeof import('preact/hooks')['useState']
}
